### ISSUE TITLE
A minor question in dsac.py

### ISSUE THREAD

**Issue by SeokjuLee** [vislearn/DSACLine#3]
In the following line in a below link,
https://github.com/vislearn/DSACLine/blob/60f29a75bcb423e7a96cb3320522c7cfa42544fd/dsac.py#L45

Shouldn't it be "torch.abs(x[idx1] - x[idx2]) > 0.01" for the inlier searching?

**Comment by ebrach** [comment]
Hi,

that's not the inlier search (see __soft_inlier_cout() for that). This line assures that points used to create a hypothesis are not too close together, as the slope would be unstable.

Kind regards,
Eric
